### PR TITLE
add translation in Italian and German

### PR DESCRIPTION
**Pull request by abonte**

### CODE REVIEW

**Comment by abonte** [comment]
The project is terrific! Thank you for generating the map!
@EqualStreetNames @jbelien  Is there any chance that the issue will be reviewed?

**Comment by jbelien** [comment]
Hello @abonte,

Thanks for your contribution (and the kind words).
I didn't see your PR because I'm only watching the repository I'm maintaining ([main repository](https://github.com/EqualStreetNames/equalstreetnames), [template repository](https://github.com/EqualStreetNames/equalstreetnames-template), and [Brussels repository](https://github.com/EqualStreetNames/equalstreetnames-brussels)).

Thanks for the ping, I'll review it right now.

I'm looking for a maintainer for this repository, would you be interested ?

**Review by jbelien — APPROVED** [review]

**Comment by jbelien** [comment]
https://bolzano.equalstreetnames.eu/ has been updated 🚀

**Comment by abonte** [comment]
Yes, I'm interested, I will gladly help the project. Thank you!

**Comment by jbelien** [comment]
Awesome!
Welcome on board.

You should have received an invite to join @EqualStreetNames/bolzano !
Once you join the team you'll receive admin rights on this repository.

**Pull request merged**
